version: "3.8"

services:
    backend:
        # image: vaninanton/laravel-demo:backend
        build:
            context: .
            dockerfile: ./.docker/backend/Dockerfile
        entrypoint: /usr/local/bin/docker-php-entrypoint-dev
        command: ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisord.conf"]
        volumes:
            - ./:/var/www/html
            - vendor:/var/www/html/vendor
            - node_modules:/var/www/html/node_modules
            - build:/var/www/public/build
        #     - ./.docker/backend/etc/supervisord.conf:/etc/supervisord.conf
        #     - ./.docker/backend/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
        #     - ./.docker/backend/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        restart: unless-stopped
        ports:
            - 8881:80

volumes:
    vendor:
    node_modules:
    build:
